version: "3"

services:
  app:
    build: ./docker/php
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:latest
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
